# Generated by Django 3.1.4 on 2020-12-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('job_title', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('full_or_part_time', models.CharField(max_length=1)),
                ('salary_or_hourly', models.CharField(max_length=250)),
                ('typical_hours', models.CharField(max_length=250)),
                ('annual_salary', models.CharField(max_length=250)),
                ('hourly_rate', models.CharField(max_length=250)),
            ],
        ),
    ]
