# Generated by Django 3.1.4 on 2020-12-09 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='jon_title',
            new_name='job_title',
        ),
    ]
